theme = "blowfish"
baseURL = "https://soybenjaminba.com/"
defaultContentLanguage = "es"

enableRobotsTXT = true
summaryLength = 30
enableEmoji = true
buildDrafts = false
buildFuture = false

[pagination]
  pagerSize = 10

[imaging]
  anchor = "Center"

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[services]
  [services.googleAnalytics]
    ID = "G-F3FXMYS08Z"

[outputs]
  home = ["HTML", "RSS", "JSON"]
