[[main]]
  name = "Blog"
  url = "/posts/"
  weight = 10

[[main]]
  name = "Acerca de"
  url = "/acerca-de/"
  weight = 20

[[main]]
  name = "Etiquetas"
  url = "/tags/"
  weight = 30

[[footer]]
  name = "Etiquetas"
  url = "/tags/"
  weight = 10
