colorScheme = "slate"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]

disableImageOptimization = false
disableTextInHeader = false

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed"

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showHero = false
  showBreadcrumbs = false
  showDraftLabel = false
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showWordCount = false
  sharingLinks = ["linkedin", "whatsapp", "twitter"]
  showZenMode = false

[list]
  showHero = false
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = true
  cardView = true

[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = false
  showTableOfContents = false
  cardView = false
